sudo: required
language: java
jdk:
- openjdk11
before_install:
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
script:
- mvn clean install
notifications:
  slack:
    secure: HyoVlPknnL2zzvHCdNWb+hASyQkqZ6yBs8xcVQWp5dkFchsy4mEEy6yLaYv/KRjVUe6b31Wu/yRTQoyXOnQOjXSLV8WFoBKD0uXFKFUOctqI32kWBfQ31wraF1qy8IZCzE8JF0Db83rrWOijN5UQWD/fPSu9eD8v0eQzMK2IbcKmTeTT/JcsYkTpSPAuKcS5ESsURuAqt2xwG4KUeBgpNX1siv5i0ctTvH/3CJOaLg7uuxcry1YkpNppKKC65uvyUotpjHKmHP4cNyNshHVqJ4JHoJ0mSU4VrxQO6zqn+u7n7HgGwYOqkuOE3qw8JbK2KPVuTEdV7UzjydfgRIXX4yT0fB4D4wvAplfmzXp7mVWZRBaVVz5kSUoyp99djGsAl6TyZvdH0py/DVKMhTBfebJ6/OVR7xaoLqHtBUVKarEjhYvoHVV+jLQdrj63NcfGyv00KtKF7LbwBeFhXT3JJukTuKhpO4lP/GLi/f7LLtyY5WbTCYyExhvQZpks+E98mrYR4FwcTtVCRSHBg11MMJJckNgKkBD7B7Wkg1oILHw4GA+GXqDTF+BRdk7tCAfypTugdEA9rqGi5/1ObmhxzpwLGm8ztnExlWrW/deNNvAyuVsa5MTItH/Va+Eh2JoM7EouUpBpf1zQ8J8MRD9rdMw/1N8qQtm9/IuyaBkElmQ=
